[package]
name = "snoozy"
version = "0.1.1"
authors = ["Tomasz Stachowiak"]
edition = "2018"

[dependencies]
failure = "0.1.3"
lazy_static = "1.2.0"
serde = "1.0.80"
serde_derive = "1.0.80"
bincode = "1.0.1"
